[package]
name = "rough"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
points_on_curve = {path = "../points_on_curve"}
euclid = "0.22"
rand = "0.8"
num-traits = "0.2"
derive_builder = "*"
